[tool.briefcase]
project_name = "Task List App"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/tasklistapp"
license = "BSD license"
author = 'KU Group 2'
author_email = "NONE"

[tool.briefcase.app.tasklistapp]
formal_name = "Task List App"
description = "Task list app for the first assignment"
icon = "src/tasklistapp/resources/tasklistapp"
sources = ['src/tasklistapp',
            'src/tasklistapp/services']
requires = [
    "httpx",
    "mysql-connector-python",
    "mysql-connector"
]


[tool.briefcase.app.tasklistapp.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.tasklistapp.linux]
requires = [
    'toga-gtk>=0.3.0.dev38',
]

[tool.briefcase.app.tasklistapp.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.tasklistapp.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.tasklistapp.windows]
requires = [
    'toga-winforms>=0.3.0.dev38',
]

# Mobile deployments
[tool.briefcase.app.tasklistapp.iOS]
requires = [
    'toga-iOS>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.tasklistapp.android]
requires = [
    'toga-android>=0.3.0.dev38'
]

[tool.briefcase.app.tasklistapp.web]
requires = [
    # Workaround; toga-web 0.3.0.dev38 doesn't include toga-core as a dependency.
    "toga-core>=0.3.0.dev38",
    "toga-web>=0.3.0.dev38",
]
style_framework = "Bootstrap v4.6"
